sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t andrewdantert/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true andrewdantert/docker-frontend npm run test -- --coverage
