sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t andrewdantert/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true andrewdantert/docker-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: "Docker-frontend"
  env: "Dockerfrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-574930369550"
  bucket_path: "Docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"